restaurant_ordering_system/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

restaurant_ordering_system/restaurant_ordering_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from restaurant_website.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('restaurant_website.urls', namespace='restaurant')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

restaurant_ordering_system/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views as custom_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', custom_views.RegisterView.as_view(), name='register'),
    path('profile/', custom_views.ProfileView.as_view(), name='profile'),
    path('confirm_email/<int:pk>', custom_views.ConfirmPage.as_view(), name='confirm_email'),

    path('password-change/', views.UserPasswordChange.as_view(),
         name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy("users:password_reset_complete"),
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

restaurant_ordering_system/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """Класс пользователя"""

    email = models.EmailField(unique=True, verbose_name='Почта')
    phone = models.CharField(max_length=35, verbose_name='Телефон', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес доставки', null=True, blank=True)
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('first_name',)

restaurant_ordering_system/users/forms.py
from django.contrib.auth import forms as auth_forms, get_user_model
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

from .models import User


class UserRegisterForm(auth_forms.UserCreationForm):
    """Форма для регистрации пользователя."""
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone', 'address', 'password1', 'password2')


class UserProfileForm(auth_forms.UserChangeForm):
    """Форма для изменения профиля пользователя."""
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'address', 'phone')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()


class UserPasswordChangeForm(PasswordChangeForm):
    """Форма для изменения пароля пользователя."""

    old_password = forms.CharField(label="Старый пароль",
                                   widget=forms.PasswordInput(
                                       attrs={'class': 'form-input'})
                                   )
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(
                                        attrs={'class': 'form-input'})
                                    )
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(
                                        attrs={'class': 'form-input'})
                                    )

    class Meta:
        """Метаданные для формы изменения пароля."""
        model = get_user_model()
        fields = ['old_password', 'new_password1', 'new_password2']

    def __str__(self):
        """Возвращает строковое представление формы."""
        return "UserPasswordChangeForm"

restaurant_ordering_system/users/views.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, TemplateView

from . import forms
from .forms import UserPasswordChangeForm
from .models import User
from .services import sendmail


class RegisterView(CreateView):
    """Регистрация пользователя, отправка запроса верификации на почту"""
    model = User
    form_class = forms.UserRegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('restaurant:home_restaurant')

    def form_valid(self, form):
        if form.is_valid:
            fields = form.save()
            sendmail(
                f'Для верификации почты пройдите по '
                f'ссылке http://127.0.0.1:8005/users/confirm_email/{fields.pk}',
                (fields.email,),
            )
        return super().form_valid(form)


class ConfirmPage(TemplateView):
    """Подтверждение почты"""
    template_name = 'registration/mail_verified.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        if User.objects.filter(pk=pk).exists():
            user = User.objects.get(pk=pk)
            user.is_active = True
            user.is_staff = True
            user.save()
        context_data['pk'] = pk
        return context_data


class ProfileView(UpdateView):
    """Просмотреть профиль пользователя"""
    model = User
    form_class = forms.UserProfileForm
    success_url = reverse_lazy('home_restaurant')

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        """Возвращает URL для перенаправления после успешного изменения пароля."""
        return reverse_lazy('users:profile')


class UserPasswordChange(PasswordChangeView):
    """Изменить пароль"""
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = 'users/password_change_form.html'

restaurant_ordering_system/users/templates/users/password_change_done.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
<div class ="modal">
  <h1>Пароль успешно изменен!</h1>
  <p class="pswd-reset"> <a href="{% url 'users:profile' %}">Вернуться в профиль {{user.username}}</a></p>
</div>
{% endblock %}

restaurant_ordering_system/users/templates/users/password_change_form.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
<div class ="modal">
  <h1>Изменение пароля</h1>

  <form  class="modal-content animate" method="post">
    <div class="auth_popup">
      {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
      {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
      {% endfor %}

      <p><button type="submit">Изменить пароль</button></p>
    </div>
  </form>

</div>
{% endblock %}

restaurant_ordering_system/users/templates/users/password_reset_complete.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
<div class ="modal">
  <h1>Пароль изменен</h1>

  <p class="pswd-reset">Поздравляем! Вы успешно изменили пароль своего аккаунта.
    <a href="{% url 'users:login' %}"> Вход в систему.</a>
  </p>

</div>
{% endblock %}

restaurant_ordering_system/users/templates/users/password_reset_confirm.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
<div class ="modal">
  <h1>Новый пароль</h1>

  <form class="modal-content animate" method="post">
    <div class="auth_popup">
      {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
      {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
      {% endfor %}

      <p><button type="submit">Сохранить</button></p>
    </div>
  </form>

</div>
{% endblock %}

restaurant_ordering_system/users/templates/users/password_reset_done.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
{% load i18n %}

<div class ="modal">
  <h1>Сброс пароля</h1>
  <div class="message-reset-psw">
    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>
    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>
  </div>
</div>
{% endblock %}

restaurant_ordering_system/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at
{{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

restaurant_ordering_system/users/templates/users/password_reset_form.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
<div class ="modal">
  <h1>Восстановление пароля</h1>

  <form class="modal-content animate" method="post">
    <div class="auth_popup">
      {% csrf_token %}

      {% for f in form %}
        <p class="reset-psw"><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
      {% endfor %}

      <p><button type="submit">Отправить на E-mail</button></p>
    </div>
  </form>

</div>
{% endblock %}

restaurant_ordering_system/users/templates/users/user_form.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}
<h3>Профиль</h3>
<div class="user-profile">
  <form method="POST" class="profile" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
  <span class="psw"><a href="{% url 'users:password_change' %}">Сменить пароль?</a></span>
</div>

{% endblock %}