restaurant_ordering_system/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

restaurant_ordering_system/restaurant_ordering_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from restaurant_website.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('restaurant_website.urls', namespace='restaurant')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

restaurant_ordering_system/users/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views

from . import views as custom_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', custom_views.RegisterView.as_view(), name='register'),
    path('profile/', custom_views.ProfileView.as_view(), name='profile'),
    path('confirm_email/<int:pk>', custom_views.ConfirmPage.as_view(), name='confirm_email'),

    path('password-change/', views.UserPasswordChange.as_view(),
         name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='password_change_done'),

    path('password-reset/',
         PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy("users:password_reset_complete"),
         ),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

restaurant_ordering_system/templates/base_restaurant.html
<!DOCTYPE html>
{% load static %}
{% load restaurant_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>КУХНЯ</title>
    <link type="text/css" href="{% static 'restaurant/css/style.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/styler.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/stylebasket.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/styleorder.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/styles.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/styleauth.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/styleproduct.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'restaurant/css/style_about.css' %}" rel="stylesheet">
</head>

<body>
  <div class="topnav">
    {% get_menu as menu %}
    {% for m in menu %}
      <a href="{% url m.url_name %}">{{m.title}}</a>
    {% endfor %}
    {% if  user.is_authenticated %}
      <a href="{% url 'users:logout' %}">Выйти</a>
      <a href="{% url 'users:profile' %}" style="float: left">{{user.first_name}}</a>
    {% else %}
      <a href="{% url 'users:login' %}">Войти</a>
    {% endif %}
  </div>
  <div class="wrapper">
    <div class="page">
      {% block content %} {% endblock %}
    </div>
  </div>

  <p onclick="topFunction()" id="myBtn" class="myBtn" title="Вверх">Вверх</p>

  <div class="footer">
    <div class="contact-information">
      <p>ООО"Кухня" (Юридическое название пиццерии) </p>
      <p>Индекс, город, улица, дом, этаж пиццерии</p>
      <p>Номер телефона: 7(***)******* </p>
    </div>
    <div class="social-media">
      <p>Наши социальные сети:</p>
      <a href="https://www.instagram.com" target="_blank" class="instagram">
        <img src="../../media/social/free-icon-instagram-2111463.png" alt="Instagram">
      </a>
      <a href="https://www.whatsapp.com/" target="_blank" class="whatsapp">
        <img src="../../media/social/free-icon-whatsapp-2504957.png" alt="Whatsapp"/>
      </a>
      <a href="https://vk.com/" target="_blank" class="vk">
        <img src="../../media/social/free-icon-vk-2504953.png" alt="Vk"/>
      </a>
    </div>
  </div>

  <script>
    window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("myBtn").style.display = "block"; // Показываем кнопку
        } else {
            document.getElementById("myBtn").style.display = "none"; // Скрываем кнопку
        }
    }

    function topFunction() {
        document.body.scrollTop = 0; // Для Safari
        document.documentElement.scrollTop = 0; // Для Chrome, Firefox, IE и Opera
    }
  </script>
</body>
</html>