restaurant_ordering_system/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

restaurant_ordering_system/orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),

]

restaurant_ordering_system/restaurant_ordering_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from restaurant_website.views import page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('restaurant_website.urls', namespace='restaurant')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

restaurant_ordering_system/restaurant_website/urls.py
from django.urls import path, register_converter, converters
from . import views
from .views import HomePageView

app_name = 'restaurant_website'
#register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    path('', views.home_restaurant, name='home_restaurant'),
    path('about/', views.about, name='about'),
    path('product/<slug:product_slug>', views.product_detail, name='product_detail'),
    path('stocks/', views.stocks, name='stocks'),
    path('product/', HomePageView.as_view, name='product'),
    path('', HomePageView.as_view, name='home_restaurant'),
]

restaurant_ordering_system/cart/models.py
from django.db import models

# Create your models here.

restaurant_ordering_system/restaurant_website/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """Категории товаров"""
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['-pk']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_available=Menu.Status.AVAILABILITY)


class Menu(models.Model):
    """Товары пиццерии"""
    class Status(models.IntegerChoices):
        ABSENT = 0, 'Отсутствует'
        AVAILABILITY = 1, 'Вналичие'

    category = models.ForeignKey(Category, on_delete=models.PROTECT, related_name='product', verbose_name='Категория')
    name_product = models.CharField(max_length=200, verbose_name='Наименование блюда')
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(max_length=500, null=True, verbose_name='Состав')
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name='Цена')
    is_available = models.BooleanField(choices=Status.choices, default=Status.AVAILABILITY, verbose_name='Наличие')
    image = models.ImageField(upload_to="products/%Y/%m/%d", blank=True, default='Добавить изображение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в меню')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')

    objects = models.Manager()
    available = AvailableManager()

    class Meta:
        ordering = ('name_product',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.name_product

    def get_absolute_url(self):
        return reverse('restaurant_website:product_detail',  args=[self.slug])


class Messages(models.Model):
    """Сообщения отправленные для пиццерии"""
    sender_name = models.CharField(max_length=50, verbose_name='Имя')
    phone = models.CharField(max_length=11, verbose_name='Телефон', null=True, blank=True)
    email = models.EmailField(verbose_name='Почта')
    message = models.TextField(max_length=2500, null=True, verbose_name='Сообщение')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата отправления письма')

    def __str__(self):
        return self.email - self.message

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

restaurant_ordering_system/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """Форма для добавления товаров в корзину"""
    quantity = forms.TypedChoiceField(label='Количество',
                                      choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

restaurant_ordering_system/restaurant_website/forms.py
from django import forms

from .models import Messages


class MessagesForm(forms.ModelForm):
    """Форма для отправления сообщения пиццерии"""

    class Meta:
        model = Messages
        fields = ['sender_name', 'phone', 'email', 'message']
        widget = {
            'sender_name': forms.TextInput(attrs={'class': 'form-input'}),
            'phone': forms.TextInput(attrs={'class': 'form-input',
                                            'pattern': '[0-9]*',
                                            'title': 'Пожалуйста, введите только цифры'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'message': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        }

restaurant_ordering_system/cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from cart.cart import Cart
from cart.forms import CartAddProductForm
from restaurant_website.models import Menu


@require_POST
def cart_add(request, product_id):
    """Добавление товаров в корзину"""
    cart = Cart(request)
    product = get_object_or_404(Menu, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
        return redirect('restaurant_website:home_restaurant')  # Перенаправление на страницу корзины
    else:
        print("Form errors:", form.errors)  # Вывод ошибок формы для отладки
        return redirect('restaurant_website:product_detail', product_slug=product.slug)


@require_POST
def cart_remove(request, product_id):
    """Изменение количества товаров в корзине"""
    cart = Cart(request)
    product = get_object_or_404(Menu, id=product_id)
    cart.remove(product)
    return redirect('restaurant_website:home_restaurant')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    return cart


def product_detail(request, id, slug):
    product = get_object_or_404(Menu, id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'restaurant_website/product.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

restaurant_ordering_system/restaurant_website/views.py
from django.contrib import messages
from django.http import HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect

from django.views.generic import ListView

from cart.cart import Cart
from cart.forms import CartAddProductForm
from cart.views import cart_detail
from .forms import MessagesForm

from .models import *
from .utils import menu


def home_restaurant(request):
    """Главная страница пиццерии с Меню и корзиной"""
    product = Menu.available.all()
    category = Category.objects.all()
    cart_product_form = CartAddProductForm
    cart = Cart(request)
    cart = cart_detail(cart)

    data = {
        'title': 'Главная страница',
        'menu': menu,
        'product': product,
        'category': category,
        'cart_product_form': cart_product_form,
        'cart': cart,
    }
    return render(request, 'restaurant_website/home_restaurant.html', context=data)


def product_detail(request, product_slug):
    """Просмотреть отдельный товар"""
    product = get_object_or_404(Menu, slug=product_slug)
    cart_product_form = CartAddProductForm()
    data = {
        'menu': menu,
        'product': product,
        'cart_product_form': cart_product_form,
     }
    return render(request, 'restaurant_website/product.html', context=data)


class HomePageView(ListView):
    model = Menu
    template_name = 'product.html'
    template_name1 = 'home_restaurant.html'


def about(request):
    """Отправить сообщение пиццерии"""
    if request.method == 'POST':
        form = MessagesForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Сообщение отправлено')
            return redirect('restaurant_website:about',)
    else:
        form = MessagesForm

    return render(request,'restaurant_website/about.html',
                  {'form': form})


def stocks(request):
    """Страница с акциями"""
    return render(request, 'restaurant_website/stocks.html', {'menu': menu})


def page_not_found(request, exception):
    return HttpResponseNotFound("<h1>Страница не найдена</h1>")

restaurant_ordering_system/restaurant_website/templates/restaurant_website/about.html
{% extends 'base_restaurant.html' %}
{% load static %}

{% block content %}

  {% if messages %}
    {% for message in messages %}
   <h3> {{ message }}</h3>
    {% endfor %}
  {% endif %}

<div class="contact">
  <div style="text-align:center">
    <h2>Загляните за пиццей или оставьте нам сообщение:</h2>
  </div>
  <div class="row">
    <div class="column-about">
      <div id="map" style="width:100%;height:500px"></div>
    </div>
    <div class="column-about">
      <form action="{% url 'restaurant_website:about' %}"  method="post" enctype="multipart/form-data" class="form-contact">
        {% csrf_token%}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for f in form %}
        <p> <label class="form-label" for="{{ f.id_for_label }}"> {{f.label }}</label>{{ f }}</p>
        <div class="form-error">{{ f.errors }}</div>
        {% endfor%}
        <p><input type="submit" value="Отправить"></p>
      </form>
    </div>
  </div>
</div>

<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
ymaps.ready(init);
function init() {
var myMap = new ymaps.Map("map", {
center: [55.76, 37.64], // Координаты центра карты
zoom: 10 // Уровень масштабирования
});
}
</script>

{% endblock %}

restaurant_ordering_system/restaurant_website/templates/restaurant_website/cart.html
{% extends 'home_restaurant.html' %}
{% block cart %}

{% include 'cart/detail.html' %}
{% endblock %}

restaurant_ordering_system/restaurant_website/templates/restaurant_website/home_restaurant.html
{% extends 'base_restaurant.html' %}
{% load static %}
{% block content %}

  <div class="header">
    <div class="header_text">КУХНЯ</div>
  </div>

  <div class="menu">
    <div class="navbar">
      {% for cat in category %}
        <a href="#{{cat.slug}}">{{cat.name}}</a>
      {% endfor %}
    </div>

    <div class="section">
      <div class="content">
        <ul>
          {% for cat in category %}
            <li>
              <div class="category">
                <div id="{{cat.slug}}"></div>
                <h1> {{cat.name}} </h1>
                {% for pr in product %}
                  {% if pr.category_id == cat.id %}
                    <div class="column">
                      <div class="product">
                        <a href="{{ pr.get_absolute_url}}">
                          <img id="{{pr.name_product}}" src="{{pr.image.url}}" style="width:100%" alt="{{ pr.name_product}}">
                        </a>
                        <div class="container">
                          <h2>{{pr.name_product}}</h2>
                          <p>{{pr.description}}</p>
                          <h2>{{pr.price}} ₽</h2>
                          <form action="{% url 'cart:cart_add' pr.id %}" method="post">
                            {% csrf_token %}
                            {{ cart_product_form }}
                            <input style="width: 85%" type="submit" value="Добавить в корзину">
                          </form>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                {% endfor %}
              </div>
            </li>
          {% endfor %}
        </ul>
      </div>

      <div class="basket">
        {% with total_items=cart|length %}
          {% if total_items > 0 %}
            <h1>Корзина ({{total_items }})</h1>
          {% else %}
            <h2>Ваша корзина пуста</h2>
          {%endif%}
        {%endwith%}

        <div class="basket-inf">
          {% for item in cart %}
            {% with product=item.product %}
              <div class="item-in-basket">
                <a href="{{ product.get_absolute_url }}">
                  <img src="{% if product.image %}{{ product.image.url }}{% endif %}"
                       style="width: 51px; height: 50px;">
                </a>
                <p>{{ product.name_product }}</p>
                <form action="{% url 'cart:cart_remove' product.id %}" method="post" style="display:inline;">
                  {% csrf_token %}
                  <input type="hidden" name="product_id" value="{{ product.id }}">
                  <span onclick="this.closest('form').submit();" class="remove-item" title="Удалить товар">×</span>
                </form>
              </div>

              <div class="item-actions">
                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                  {% csrf_token %}
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.override }}
                  <input type="submit" value="Изменить">
                </form>
                <p class="num">{{ item.total_price }}₽</p>
              </div>

              <hr style="margin: 4px;">

            {% endwith %}
          {% endfor %}

          {% with total_items=cart|length %}
            {% if total_items > 0 %}
              <div class="total">
                <p><b>Сумма заказа:</b></p>
                <p class="num"><b>{{ cart.get_total_price }} ₽</b></p>
              </div>

              <div class="place-an-order">
                <p class="text-right">
                  <a href="{% url 'orders:order_create' %}" class="button">Оформить заказ</a>
                </p>
              </div>
            {%endif%}
          {%endwith%}

        </div>
      </div>
    </div>
  </div>

{% endblock %}

restaurant_ordering_system/restaurant_website/templates/restaurant_website/product.html
{% extends 'base_restaurant.html' %}
{% load static %}
{% block content %}
<div class="product-detail">
  <div class="content-pr">

    <h1 style="text-align: center; padding: 3%">{{product.name_product}}</h1>

    <div class="pr" style="display: flex; flex-wrap: wrap; justify-content: center; text-align: center; padding: 5%">
      {% if product.image %}
      <p><img class="img-article-left" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2); border-radius: 4%" src="{{product.image.url}}"></p>
      {% endif %}

      <div class="pr-descriptio">{{product.description}} <br/><br/> {{product.price}} ₽

      <form action="{% url 'cart:cart_add' product.id %}" method="post" style= "margin-bottom: 5%">
        {{ cart_product_form }}
        {% csrf_token %}
        <input style="padding: 1%; height: auto" type="submit" value="Добавить в корзину">
      </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

restaurant_ordering_system/restaurant_website/templates/restaurant_website/stocks.html
{% extends 'base_restaurant.html' %}
{% load static %}
{% block content %}
<div class="coupon">
  <img src="https://i.1.creatium.io/92/e4/39/1fbeb2b083c721aa984cf79b660326e58c/357x357q8/2_1_s_1_maya231.png"
       alt="Avatar" style="width:100%;">
  <div class="stocks" style="background-color:white">
    <h2><b>ДАРИМ ПЕППЕРОННИ</b></h2>

    <p>
        При заказе двух пицц одного размера, дарим легендарную пиццу "Пепперони" 26 см.
        В акции участвуют пиццы 30см и 35см. Акции и скидки не суммируются.
        Акция действует только при заказах через сайт пиццерии или в самой пиццерии,
        и не распространяется на доставку. Акция действует только один раз. В праздничные дни акция не действует.
    </p>
      <div class="stock">
        <p> Промо-код: <span class="promo">BOH232</span></p>
        <p class="expire">Действует: по будням с 10:00 до 16:00</p>
      </div>
  </div>

</div>
{% endblock %}